package de.htw.ai.kbe.config;

import javax.ws.rs.ApplicationPath;
import org.glassfish.jersey.server.ResourceConfig;

import de.htw.ai.kbe.auth.AuthorizationFilter;
import de.htw.ai.kbe.di.DependencyBinder;
import de.htw.ai.kbe.exceptions.UnhandledExceptionFilter;

@ApplicationPath("/rest")
public class MyApplication extends ResourceConfig
{
	public MyApplication()
	{
		register(new DependencyBinder());
		register(AuthorizationFilter.class);
        register(UnhandledExceptionFilter.class);
		packages("de.htw.ai.kbe.services");
	}
}

//<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: userid of: de.htw.ai.kbe.auth.StandardUser [SELECT u FROM de.htw.ai.kbe.auth.StandardUser u WHERE u.userid LIKE :userid]</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: userid of: de.htw.ai.kbe.auth.StandardUser [SELECT u FROM de.htw.ai.kbe.auth.StandardUser u WHERE u.userid LIKE :userid]
//		org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:432)
//		org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
//		org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
//	</pre><p><b>Root Cause</b></p><pre>java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: userid of: de.htw.ai.kbe.auth.StandardUser [SELECT u FROM de.htw.ai.kbe.auth.StandardUser u WHERE u.userid LIKE :userid]
//		org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:133)
//		org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
//		org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:164)
//		org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:670)
//		org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:686)
//		org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
//		de.htw.ai.kbe.auth.StandardUserPostgresRegistry.byUserId(StandardUserPostgresRegistry.java:143)
//		de.htw.ai.kbe.auth.StandardUserPostgresRegistry.byUserId(StandardUserPostgresRegistry.java:16)
//		de.htw.ai.kbe.services.AuthenticationWebService.getAuthentication(AuthenticationWebService.java:41)
//		sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//		sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//		java.lang.reflect.Method.invoke(Method.java:498)
//		org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
//		org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
//		org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
//		org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
//		org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:316)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:298)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:268)
//		org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
//		org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
//		org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
//		org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
//		org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
//		org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
//	</pre><p><b>Root Cause</b></p><pre>org.hibernate.QueryException: could not resolve property: userid of: de.htw.ai.kbe.auth.StandardUser [SELECT u FROM de.htw.ai.kbe.auth.StandardUser u WHERE u.userid LIKE :userid]
//		org.hibernate.QueryException.generateQueryException(QueryException.java:120)
//		org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103)
//		org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:217)
//		org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141)
//		org.hibernate.engine.query.spi.HQLQueryPlan.&lt;init&gt;(HQLQueryPlan.java:115)
//		org.hibernate.engine.query.spi.HQLQueryPlan.&lt;init&gt;(HQLQueryPlan.java:77)
//		org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
//		org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:553)
//		org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:662)
//		org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:686)
//		org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
//		de.htw.ai.kbe.auth.StandardUserPostgresRegistry.byUserId(StandardUserPostgresRegistry.java:143)
//		de.htw.ai.kbe.auth.StandardUserPostgresRegistry.byUserId(StandardUserPostgresRegistry.java:16)
//		de.htw.ai.kbe.services.AuthenticationWebService.getAuthentication(AuthenticationWebService.java:41)
//		sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//		sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//		java.lang.reflect.Method.invoke(Method.java:498)
//		org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
//		org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
//		org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
//		org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
//		org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:316)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:298)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:268)
//		org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
//		org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
//		org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
//		org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
//		org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
//		org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
//	</pre><p><b>Root Cause</b></p><pre>org.hibernate.QueryException: could not resolve property: userid of: de.htw.ai.kbe.auth.StandardUser
//		org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:62)
//		org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:56)
//		org.hibernate.persister.entity.AbstractEntityPersister.toType(AbstractEntityPersister.java:1859)
//		org.hibernate.hql.internal.ast.tree.FromElementType.getPropertyType(FromElementType.java:393)
//		org.hibernate.hql.internal.ast.tree.FromElement.getPropertyType(FromElement.java:512)
//		org.hibernate.hql.internal.ast.tree.DotNode.getDataType(DotNode.java:665)
//		org.hibernate.hql.internal.ast.tree.DotNode.prepareLhs(DotNode.java:264)
//		org.hibernate.hql.internal.ast.tree.DotNode.resolve(DotNode.java:204)
//		org.hibernate.hql.internal.ast.HqlSqlWalker.resolve(HqlSqlWalker.java:1040)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.expr(HqlSqlBaseWalker.java:1290)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.exprOrSubquery(HqlSqlBaseWalker.java:4707)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.comparisonExpr(HqlSqlBaseWalker.java:4319)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2138)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:815)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:609)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:313)
//		org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:261)
//		org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:266)
//		org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:189)
//		org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141)
//		org.hibernate.engine.query.spi.HQLQueryPlan.&lt;init&gt;(HQLQueryPlan.java:115)
//		org.hibernate.engine.query.spi.HQLQueryPlan.&lt;init&gt;(HQLQueryPlan.java:77)
//		org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
//		org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:553)
//		org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:662)
//		org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:686)
//		org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
//		de.htw.ai.kbe.auth.StandardUserPostgresRegistry.byUserId(StandardUserPostgresRegistry.java:143)
//		de.htw.ai.kbe.auth.StandardUserPostgresRegistry.byUserId(StandardUserPostgresRegistry.java:16)
//		de.htw.ai.kbe.services.AuthenticationWebService.getAuthentication(AuthenticationWebService.java:41)
//		sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//		sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//		java.lang.reflect.Method.invoke(Method.java:498)
//		org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
//		org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
//		org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
//		org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
//		org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
//		org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
//		org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:316)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:298)
//		org.glassfish.jersey.internal.Errors.process(Errors.java:268)
//		org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
//		org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
//		org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
//		org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
//		org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
//		org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
//		org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
//	</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.14</h3></body></html>